import { Property, Agent, AppConfig, Testimonial } from "./types";

// NOTE: import.meta.glob is removed because we use the public folder now.
// The website will automatically look in the public folder for paths starting with "/"

export const APP_CONFIG: AppConfig = {
  locale: "en-IN",
  currency: "INR",
  companyInfo: {
    name: "V Horizon Properties",
    address: "Shop no G-03, La Gracia Mall, Crossings Republik, Ghaziabad, Uttar Pradesh",
    phone: "+91 9217564977",
    email: "vhorizonproperties@gmail.com",
  },
};

export const agents: Agent[] = [
  {
    id: "ag_01",
    name: "Jatin Sharabu ",
    role: "Senior Broker",
    specialty: "Studio Apartments",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=400",
    phone: "+91 8700273095",
    email: "vhorizonproperties@gmail.com",
    bio: "With over 15 years of experience in Studio Apartments.",
  },
  {
    id: "ag_02",
    name: "Aarav Dhaka",
    role: "Director of Sales",
    specialty: "Luxury Penthouses",
    image: "/Aarav.jpeg",
    phone: "+91 97604 40610",
    email: "vhorizonproperties@gmail.com",
    bio: "Aarav leads our operations with a keen eye for ultra-luxury penthouses and premium properties.",
  },
  {
    id: "ag_03",
    name: "Utkarsh Badhoutia",
    role: "Director",
    specialty: "commercial ",
    image: "/Utkarsh.png",
    phone: "+91 99106 86088",
    email: "vhorizonproperties@gmail.com",
    bio: "Utkarsh brings 10 years of expertise in commercial properties, with a focus on NCR's commercial properties.",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Rajesh Gupta",
    role: "Tech Entrepreneur",
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=400",
    quote: "V Horizon Properties made finding our dream home in Noida effortless. Their attention to detail and understanding of our needs was exceptional.",
    rating: 5,
    propertyType: "Villa",
  },
  {
    id: "t2",
    name: "Ananya Patel",
    role: "Film Producer",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=400",
    quote: "The team at V Horizon helped us find the perfect penthouse with stunning views. Their professionalism and market knowledge is unmatched.",
    rating: 5,
    propertyType: "Penthouse",
  },
  {
    id: "t3",
    name: "Vikram Singh",
    role: "Investment Banker",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=400",
    quote: "Exceptional service from start to finish. They understood exactly what we were looking for and delivered beyond our expectations.",
    rating: 5,
    propertyType: "Estate",
  },
];

export const properties: Property[] = [
  {
    id: 101,
    title: "Pind Balluchi – Panchsheel Square Mall",
    location: "Ghaziabad",
    area: "Crossings Republik",
    price: 36000000,
    type: "commercial",
    status: "sale",
    beds: 0,
    baths: 2,
    sqft: 3700,
    superArea: 3700,
    carpetArea: 2900,
    currentRent: 182000,
    amenities: ["Main Road Facing", "3rd Floor", "Leased to National Brand", "High Visibility", "50,000+ Flats Nearby", "Stable Rental Income"],
    // FIXED: Using direct path to public folder
    heroImage: "/images/pind/1.jpeg",
    gallery: [
      "/images/pind/1.jpeg",
      "/images/pind/2.jpeg",
      "/images/pind/3.jpeg",
      "/images/pind/4.jpeg",
    ],
    description: "Own a prime, income-generating commercial asset at Panchsheel Square Mall, Crossings Republik. Currently leased to Pind Balluchi Restaurant, a well-known national brand. Main road facing unit on 3rd floor with excellent visibility from Crossings main roundabout. Rent to be revised to ₹2,00,000/month from Feb 2026. Located within 2 km radius of 50,000+ residential flats. Ideal for investors seeking stable rental income & long-term appreciation.",
    agentId: "ag_01",
    createdAt: "2026-01-05",
  },
  {
    id: 102,
    title: "La Gracia Mall – Premium Retail Space",
    location: "Ghaziabad",
    area: "Crossings Republik",
    price: 0,
    type: "commercial",
    status: "lease",
    beds: 0,
    baths: 2,
    sqft: 2860,
    superArea: 2860,
    carpetArea: 1950,
    amenities: ["Two-Side Open Unit", "20 Ft Front Entry", "20 Ft Back Entry", "Basement Parking", "Front Parking", "High Visibility", "Main Road Access"],
    heroImage: "/images/gracia/1.jpeg",
    gallery: [
      "/images/gracia/1.jpeg",
      "/images/gracia/2.jpeg",
    ],
    description: "Premium retail space at La Gracia Mall with 20 ft. wide front and back entries (two-side open unit). Dimension: 20 Ft. by 95 Ft. Easily accessible and prominently visible from the main road with adequate parking in both basement and front of store. Ideal for retail outlets, showrooms, restaurants, banks and fitness studios looking to establish a strong presence in a high visibility area. Shop No: G04, G03, G41, G42, G43, G44, G45.",
    agentId: "ag_02",
    createdAt: "2026-01-04",
  },
  {
    id: 103,
    title: "Pizza Hut Outlet – Paramount Spectrum Hi-Street",
    location: "Ghaziabad",
    area: "Crossings Republik",
    price: 0,
    type: "commercial",
    status: "lease",
    beds: 0,
    baths: 2,
    sqft: 1441,
    superArea: 1441,
    carpetArea: 1000,
    amenities: ["Main Road Facing", "First Floor", "High Footfall", "Ample Parking", "Ready to Move", "Currently Rented to Pizza Hut"],
    heroImage: "/images/pizza/1.jpeg",
    gallery: [
      "/images/pizza/1.jpeg",
      "/images/pizza/2.jpeg",
      "/images/pizza/3.jpeg",
    ],
    description: "Commercial shop for lease at Paramount Spectrum Hi-Street, Shop No FF-10 on First Floor. Currently rented to Pizza Hut (running outlet) with lease expiring soon. Prime location on high-street commercial retail zone, ideal for restaurants, cafes, branded retail, clinics, salons, showrooms, electronics, banks/ATMs, etc. Excellent visibility & high footfall, surrounded by high-density residential townships. Well maintained, ready-to-move property.",
    agentId: "ag_03",
    createdAt: "2026-01-03",
  },
  {
    id: 104,
    title: "Paramount Spectrum Hi-Street – KFC Outlet",
    location: "Ghaziabad",
    area: "Crossings Republik",
    price: 70000000,
    type: "commercial",
    status: "sale",
    beds: 0,
    baths: 1,
    sqft: 4140,
    superArea: 4140,
    carpetArea: 2800,
    amenities: ["Main Road Facing", "First Floor", "High Footfall", "Ample Parking", "Currently Rented to KFC"],
    currentRent: 280000,
    // FIXED: Using direct path to public folder
    heroImage: "/images/kfc/1.jpeg",
    gallery: [
      "/images/kfc/1.jpeg",
      "/images/kfc/2.jpeg",
      "/images/kfc/3.jpeg",
      "/images/kfc/4.jpeg",
    ],
    description: "Commercial shop for sale at Paramount Spectrum Hi-Street, Shop No FF-10 on First Floor. Currently rented to KFC. Prime location on high-street commercial retail zone, ideal for restaurants, cafes, branded retail, clinics, salons, showrooms, electronics, banks/ATMs, etc. Excellent visibility & high footfall, surrounded by high-density residential townships. Well maintained",
    agentId: "ag_03",
    createdAt: "2026-01-03",
  },
  {
    id: 105,
    title: "La Gracia Mall – Premium Retail Space",
    location: "Ghaziabad",
    area: "Crossings Republik",
    price: 70000000,
    type: "commercial",
    status: "sale",
    beds: 0,
    baths: 2,
    sqft: 2860,
    superArea: 2860,
    carpetArea: 1950,
    amenities: ["Two-Side Open Unit", "20 Ft Front Entry", "20 Ft Back Entry", "Basement Parking", "Front Parking", "High Visibility", "Main Road Access"],
    heroImage: "/images/gracia/1.jpeg",
    gallery: [
      "/images/gracia/1.jpeg",
      "/images/gracia/2.jpeg",
    ],
    description: "Premium retail space at La Gracia Mall with 20 ft. wide front and back entries (two-side open unit). Dimension: 20 Ft. by 95 Ft. Easily accessible and prominently visible from the main road with adequate parking in both basement and front of store. Ideal for retail outlets, showrooms, restaurants, banks and fitness studios looking to establish a strong presence in a high visibility area. Shop No: G04, G03, G41, G42, G43, G44, G45.",
    agentId: "ag_02",
    createdAt: "2026-01-04",
  },
  {
    id: 106,
    title: "WellBazaar – Panchsheel Wellington",
    location: "Ghaziabad",
    area: "Crossings Republic",
    price: 70000,
    type: "commercial",
    status: "rent",
    beds: 0,
    baths: 0,
    sqft: 1500,
    superArea: 1500,
    carpetArea: 950,
    amenities: ["Main Road Facing", "Ground Floor", "High Footfall", "Ample Parking", "24x7 Security", "Power Backup"],
    heroImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200",
    gallery: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?q=80&w=1200",
    ],
    description: "Premium commercial space in WellBazaar, Panchsheel Wellington. Ideal for retail, pharmacy, or grocery store. Located in a high-density residential area ensuring guaranteed footfall. Ready for fit-outs.",
    agentId: "ag_02",
    createdAt: "2026-01-06",
  },
  {
    id: 107,
    title: "Executive Studio – Gaur City",
    location: "Greater Noida West",
    area: "Gaur City 2",
    price: 18000,
    type: "residential",
    status: "rent",
    beds: 1,
    baths: 1,
    sqft: 650,
    superArea: 650,
    carpetArea: 520,
    amenities: ["Semi-Furnished", "AC Installed", "Gated Community", "Metro Connectivity", "Power Backup", "24x7 Security"],
    heroImage: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200",
    gallery: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1200",
    ],
    description: "Compact and efficient studio apartment ideal for young professionals. Semi-furnished with AC, located in a well-maintained gated community with excellent metro connectivity. Affordable luxury with access to all modern amenities. Walking distance to shopping centers and restaurants.",
    agentId: "ag_03",
    createdAt: "2026-01-05",
  },
  {
    id: 108,
    title: " WYNND BANQUET – Orbit Plaza Mall",
    location: "Ghaziabad",
    area: "Crossings republic",
    price: 150000000,
    type: "commercial",
    status: "sale",
    beds: 0,
    baths: 2,
    sqft: 22000,
    superArea: 22000,
    carpetArea: 12000,
    currentRent: 800000,
    amenities: ["Semi-Furnished", "AC Installed", "Gated Community", "Metro Connectivity", "Power Backup", "24x7 Security"],
    heroImage: "/images/Wind/1.jpeg",
    gallery: [
      "/images/Wind/1.jpeg",
      "/images/Wind/2.jpeg",
      "/images/Wind/3.jpeg",
      "/images/Wind/4.jpeg",
      "/images/Wind/5.jpeg",
    ],
    description: "LEASE & INCOME Monthly Rent: ₹8,00,000  Lease Term: 12 years , Escalation: 15% every 3 years, 🔒 Long-term income security",
    agentId: "ag_03",
    createdAt: "2026-01-02",
  },
  {
    id: 109,
    title: "Urban Skyline Studio - Financial District",
    location: "Noida",
    area: "Sector 16",
    price: 3500,
    type: "studio",
    status: "stay",
    perTime: "night",
    beds: 1,
    baths: 1,
    sqft: 450,
    superArea: 450,
    carpetArea: 400,
    amenities: ["High-Speed Wi-Fi", "Workstation", "Coffee Machine", "Daily Housekeeping", "Smart TV", "Metric Linen"],
    heroImage: "https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80&w=1200",
    gallery: [
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80&w=1200",
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?q=80&w=1200",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200"
    ],
    description: "Perfect for business travelers. A sleek, modern studio in the heart of the business district. Equipped with enterprise-grade Wi-Fi and ergonomic workstation. 5 minutes from Metro station.",
    agentId: "ag_01",
    createdAt: "2026-01-20",
  },
  {
    id: 110,
    title: "Cozy Garden Retreat - Quiet Zone",
    location: "Greater Noida",
    area: "Pari Chowk",
    price: 2800,
    type: "studio",
    status: "stay",
    perTime: "night",
    beds: 1,
    baths: 1,
    sqft: 500,
    superArea: 500,
    carpetArea: 480,
    amenities: ["Private Patio", "Kitchenette", "Garden View", "Pet Friendly", "Parking", "Self Check-in"],
    heroImage: "https://images.unsplash.com/photo-1595521624992-48a59aef95e3?q=80&w=1200",
    gallery: [
      "https://images.unsplash.com/photo-1595521624992-48a59aef95e3?q=80&w=1200",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200",
    ],
    description: "A peaceful ground-floor studio with a private sit-out area. Ideal for couples or solo travelers looking for a quiet break. Fully stocked kitchenette and premium bedding.",
    agentId: "ag_01",
    createdAt: "2026-01-22",
  },
  {
    id: 111,
    title: "Lux Loft - City Center",
    location: "Ghaziabad",
    area: "RDC",
    price: 500,
    type: "studio",
    status: "stay",
    perTime: "hour",
    beds: 1,
    baths: 1,
    sqft: 600,
    superArea: 600,
    carpetArea: 550,
    amenities: ["Soundproof", "Projector Setup", "Mini Bar", "Designer Interiors", "Room Service", "Valet"],
    heroImage: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?q=80&w=1200",
    gallery: [
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?q=80&w=1200",
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80&w=1200",
    ],
    description: "Experience luxury by the hour. This high-end loft features designer aesthetics, soundproofing for privacy, and a large projector screen. Perfect for short meetings or relaxation.",
    agentId: "ag_02",
    createdAt: "2026-01-25",
  },
];

export const getPropertyById = (id: number): Property | undefined => {
  return properties.find((p) => p.id === id);
};

export const getAgentById = (id: string): Agent | undefined => {
  return agents.find((a) => a.id === id);
};

export const formatPrice = (amount: number): string => {
  if (amount === 0) return "Price on Request";
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(amount);
};

export const formatPriceShort = (amount: number): string => {
  if (amount === 0) return "P.O.R.";
  if (amount >= 10000000) {
    return `₹${(amount / 10000000).toFixed(1)} Cr`;
  } else if (amount >= 100000) {
    return `₹${(amount / 100000).toFixed(1)} L`;
  }
  return formatPrice(amount);
};
