
-- Insert Initial Properties
INSERT INTO public.properties (
  id, title, location, area, price, type, status, beds, baths, sqft, 
  super_area, carpet_area, current_rent, amenities, hero_image, gallery, 
  description, agent_id, created_at
) VALUES 
(
  101,
  'Pind Balluchi – Panchsheel Square Mall',
  'Ghaziabad',
  'Crossings Republik',
  36000000,
  'commercial',
  'sale',
  0,
  2,
  3700,
  3700,
  2900,
  182000,
  ARRAY['Main Road Facing', '3rd Floor', 'Leased to National Brand', 'High Visibility', '50,000+ Flats Nearby', 'Stable Rental Income'],
  '/images/pind/1.jpeg',
  ARRAY['/images/pind/1.jpeg', '/images/pind/2.jpeg', '/images/pind/3.jpeg', '/images/pind/4.jpeg'],
  'Own a prime, income-generating commercial asset at Panchsheel Square Mall, Crossings Republik. Currently leased to Pind Balluchi Restaurant, a well-known national brand. Main road facing unit on 3rd floor with excellent visibility from Crossings main roundabout. Rent to be revised to ₹2,00,000/month from Feb 2026. Located within 2 km radius of 50,000+ residential flats. Ideal for investors seeking stable rental income & long-term appreciation.',
  'ag_01',
  '2026-01-05'
),
(
  102,
  'La Gracia Mall – Premium Retail Space',
  'Ghaziabad',
  'Crossings Republik',
  0,
  'commercial',
  'lease',
  0,
  2,
  2860,
  2860,
  1950,
  NULL,
  ARRAY['Two-Side Open Unit', '20 Ft Front Entry', '20 Ft Back Entry', 'Basement Parking', 'Front Parking', 'High Visibility', 'Main Road Access'],
  '/images/gracia/1.jpeg',
  ARRAY['/images/gracia/1.jpeg', '/images/gracia/2.jpeg'],
  'Premium retail space at La Gracia Mall with 20 ft. wide front and back entries (two-side open unit). Dimension: 20 Ft. by 95 Ft. Easily accessible and prominently visible from the main road with adequate parking in both basement and front of store. Ideal for retail outlets, showrooms, restaurants, banks and fitness studios looking to establish a strong presence in a high visibility area. Shop No: G04, G03, G41, G42, G43, G44, G45.',
  'ag_02',
  '2026-01-04'
),
(
  103,
  'Pizza Hut Outlet – Paramount Spectrum Hi-Street',
  'Ghaziabad',
  'Crossings Republik',
  0,
  'commercial',
  'lease',
  0,
  2,
  1441,
  1441,
  1000,
  NULL,
  ARRAY['Main Road Facing', 'First Floor', 'High Footfall', 'Ample Parking', 'Ready to Move', 'Currently Rented to Pizza Hut'],
  '/images/pizza/1.jpeg',
  ARRAY['/images/pizza/1.jpeg', '/images/pizza/2.jpeg', '/images/pizza/3.jpeg'],
  'Commercial shop for lease at Paramount Spectrum Hi-Street, Shop No FF-10 on First Floor. Currently rented to Pizza Hut (running outlet) with lease expiring soon. Prime location on high-street commercial retail zone, ideal for restaurants, cafes, branded retail, clinics, salons, showrooms, electronics, banks/ATMs, etc. Excellent visibility & high footfall, surrounded by high-density residential townships. Well maintained, ready-to-move property.',
  'ag_03',
  '2026-01-03'
),
(
  104,
  'Paramount Spectrum Hi-Street – KFC Outlet',
  'Ghaziabad',
  'Crossings Republik',
  70000000,
  'commercial',
  'sale',
  0,
  1,
  4140,
  4140,
  2800,
  250000,
  ARRAY['Main Road Facing', 'First Floor', 'High Footfall', 'Ample Parking', 'Currently Rented to KFC'],
  '/images/kfc/1.jpeg',
  ARRAY['/images/kfc/1.jpeg', '/images/kfc/2.jpeg', '/images/kfc/3.jpeg', '/images/kfc/4.jpeg'],
  'Commercial shop for sale at Paramount Spectrum Hi-Street, Shop No FF-10 on First Floor. Currently rented to KFC. Prime location on high-street commercial retail zone, ideal for restaurants, cafes, branded retail, clinics, salons, showrooms, electronics, banks/ATMs, etc. Excellent visibility & high footfall, surrounded by high-density residential townships. Well maintained',
  'ag_03',
  '2026-01-03'
),
(
  105,
  'La Gracia Mall – Premium Retail Space (Sale)',
  'Ghaziabad',
  'Crossings Republik',
  70000000,
  'commercial',
  'sale',
  0,
  2,
  2860,
  2860,
  1950,
  NULL,
  ARRAY['Two-Side Open Unit', '20 Ft Front Entry', '20 Ft Back Entry', 'Basement Parking', 'Front Parking', 'High Visibility', 'Main Road Access'],
  '/images/gracia/1.jpeg',
  ARRAY['/images/gracia/1.jpeg', '/images/gracia/2.jpeg'],
  'Premium retail space at La Gracia Mall with 20 ft. wide front and back entries (two-side open unit). Dimension: 20 Ft. by 95 Ft. Easily accessible and prominently visible from the main road with adequate parking in both basement and front of store. Ideal for retail outlets, showrooms, restaurants, banks and fitness studios looking to establish a strong presence in a high visibility area. Shop No: G04, G03, G41, G42, G43, G44, G45.',
  'ag_02',
  '2026-01-04'
),
(
  106,
  'WellBazaar – Panchsheel Wellington',
  'Ghaziabad',
  'Crossings Republic',
  70000,
  'commercial',
  'rent',
  0,
  2,
  1500,
  1500,
  950,
  NULL,
  ARRAY['Fully Furnished', 'Modular Kitchen', 'Main Road Facing', 'First Floor', 'High Footfall', 'Ample Parking', '24x7 Security', 'Power Backup'],
  'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200',
  ARRAY['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200', 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200', 'https://images.unsplash.com/photo-1484154218962-a197022b5858?q=80&w=1200'],
  'Beautifully furnished 3BHK apartment in the prestigious Indiabulls Greens township. Move-in ready with premium furniture, fully equipped modular kitchen, and access to resort-style amenities including swimming pool, clubhouse, and gymnasium. Perfect for corporate executives and families.',
  'ag_02',
  '2026-01-06'
),
(
  107,
  'Executive Studio – Gaur City',
  'Greater Noida West',
  'Gaur City 2',
  18000,
  'residential',
  'rent',
  1,
  1,
  650,
  650,
  520,
  NULL,
  ARRAY['Semi-Furnished', 'AC Installed', 'Gated Community', 'Metro Connectivity', 'Power Backup', '24x7 Security'],
  'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200',
  ARRAY['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200', 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200', 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1200'],
  'Compact and efficient studio apartment ideal for young professionals. Semi-furnished with AC, located in a well-maintained gated community with excellent metro connectivity. Affordable luxury with access to all modern amenities. Walking distance to shopping centers and restaurants.',
  'ag_03',
  '2026-01-05'
),
(
  108,
  'WYNND BANQUET – Orbit Plaza Mall',
  'Ghaziabad',
  'Crossings republic',
  140000000,
  'commercial',
  'sale',
  0,
  2,
  22000,
  22000,
  12000,
  800000,
  ARRAY['Semi-Furnished', 'AC Installed', 'Gated Community', 'Metro Connectivity', 'Power Backup', '24x7 Security'],
  '/images/Wind/1.jpeg',
  ARRAY['/images/Wind/1.jpeg', '/images/Wind/2.jpeg', '/images/Wind/3.jpeg', '/images/Wind/4.jpeg', '/images/Wind/5.jpeg'],
  'LEASE & INCOME Monthly Rent: ₹8,00,000  Lease Term: 12 years , Escalation: 15% every 3 years, 🔒 Long-term income security',
  'ag_03',
  '2026-01-02'
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  price = EXCLUDED.price,
  description = EXCLUDED.description;
